# Generated by Django 5.1.2 on 2024-10-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
            ],
        ),
    ]
