# Generated by Django 5.1.2 on 2024-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecins',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
