# Generated by Django 5.1.2 on 2024-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0002_medecins_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecins',
            name='photo',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
    ]
