# Generated by Django 5.1.2 on 2024-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0005_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='deplacement',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
