# Generated by Django 5.1.2 on 2024-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0006_exams_deplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
