# Generated by Django 5.1.2 on 2024-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0010_alter_medecins_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecins',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
