# Generated by Django 5.1.2 on 2024-11-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0016_patients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
    ]
