# Generated by Django 5.1.2 on 2024-11-01 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0018_remove_patients_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patients',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddField(
            model_name='patients',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
