# Generated by Django 5.1.2 on 2024-11-01 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0019_patients_age_patients_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
