# Generated by Django 5.1.2 on 2024-11-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0020_remove_patients_user_alter_patients_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='deplacement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
