# Generated by Django 5.1.2 on 2024-11-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0023_alter_exams_deplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teleconsult_app.patients'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='deplacement',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
