# Generated by Django 5.1.2 on 2024-11-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0024_rendezvous_patient_alter_exams_deplacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
