# Generated by Django 5.1.2 on 2024-11-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0026_rename_medecin_rendezvous_medecin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='medecin_id',
            new_name='medecin',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
