# Generated by Django 5.1.2 on 2024-11-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0028_rename_nom_patients_nom_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='is_active',
        ),
    ]
