# Generated by Django 5.1.2 on 2024-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0029_remove_patients_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='username',
        ),
    ]
