# Generated by Django 5.1.2 on 2024-11-02 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0030_remove_patients_age_remove_patients_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patients',
            name='password',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AddField(
            model_name='patients',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
