# Generated by Django 5.1.2 on 2024-11-02 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0031_patients_age_patients_email_patients_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='nom_prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
