# Generated by Django 5.1.2 on 2024-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0032_alter_patients_nom_prenom_alter_patients_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
