# Generated by Django 5.1.2 on 2024-11-02 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0033_alter_patients_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
