# Generated by Django 5.1.2 on 2024-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0034_alter_patients_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
