# Generated by Django 5.1.2 on 2024-11-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0038_remove_patients_user_patients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
    ]
