# Generated by Django 5.1.2 on 2024-11-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0047_medecins_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecins',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
