# Generated by Django 5.1.2 on 2024-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0008_medecins_age_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecins',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
