# Generated by Django 5.1.2 on 2024-11-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0013_patients_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='telephone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
