# Generated by Django 5.1.2 on 2024-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0014_alter_patients_age_alter_patients_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
