# Generated by Django 5.1.2 on 2024-11-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0017_remove_patients_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='date_de_naissance',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='telephone',
        ),
    ]
