# Generated by Django 5.1.2 on 2024-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0021_alter_exams_deplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='deplacement',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
