# Generated by Django 5.1.2 on 2024-11-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0025_rename_patient_rendezvous_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='medecin',
            new_name='medecin_id',
        ),
    ]
