# Generated by Django 5.1.2 on 2024-11-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0036_remove_patients_password_remove_patients_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='user',
            new_name='User',
        ),
    ]
