# Generated by Django 5.1.2 on 2024-11-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0040_patients_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='')),
                ('commentaire', models.TextField(null=True)),
            ],
        ),
    ]
