# Generated by Django 5.1.2 on 2024-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0045_medecins_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecins',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
