# Generated by Django 5.1.2 on 2024-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0046_alter_medecins_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecins',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
