# Generated by Django 5.1.2 on 2024-11-13 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleconsult_app', '0052_remove_rendezvous_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('video', 'Appel vidéo'), ('audio', 'Appel audio')], max_length=50)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsult_app.medecins')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleconsult_app.patients')),
            ],
        ),
    ]
